version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: demo_nginx
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html:rw
      - ./docker/nginx/:/etc/nginx/conf.d

  php-fpm:
    build: .docker/php
    container_name: demo_php
    volumes:
      - ./:/usr/share/nginx/html:rw
      - ./.docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini




